import fs from 'node:fs/promises';
import { extractClasses } from './extractor.js';

export async function generateTypes(filePath: string, content: string): Promise<void> {
	const classNames = extractClasses(content);
	const declarationPath = `${filePath}.d.ts`;
	const mapping = classNames.map(name => `  ${name}: "${name}";`).join('\n');
	const template = `/* Generated by Flat Style Sheets - Do not edit manually */
        export const css: string;
        export const classes: {${mapping}};
        const defaultExport: string;
        export default defaultExport;
        `;

	await fs.writeFile(declarationPath, template, 'utf-8');
}
